nodeLinker: node-modules

supportedArchitectures:
  cpu:
    - x64
    - x86
    - arm
    - arm64
    - ia32
  libc:
    - glibc
    - musl
  os:
    - darwin
    - linux
    - win32

yarnPath: .yarn/releases/yarn-4.5.0.cjs
