# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- release/*

pr:
  branches:
    include:
    - release/*
    exclude:
    - main

stages:
- stage: build
  displayName: build
  pool:
    name: On-Premise # Runs on OnPrem Windows (for now)
    demands:
    - Agent.Name -equals $(buildAgentName)
    # vmImage: 'ubuntu-latest' # Runs on Hosted Ubuntu VM
  jobs:
  - job: Build
    workspace:
      clean: all
    steps:
    - template: templates/build.yml

- stage: deploy
  dependsOn: build
  displayName: Deploy to IIS
  condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/main'),startsWith(variables['Build.SourceBranch'], 'refs/heads/release')))
  jobs:
  - deployment: DeploytoIIS
    environment:
      name: Production
      resourceType: VirtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
          - template: templates/deploy.yml
