# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pr:
  branches:
    include:
    - main
    exclude:
    - release/*

stages:
- stage: build
  displayName: build
  pool:
    name: On-Premise # Runs on OnPrem Windows (for now)
    demands:
    - Agent.Name -equals $(buildAgentName)
    # vmImage: 'ubuntu-latest' # Runs on Hosted Ubuntu VM
    jobs:
    - job: Build
      steps:
      - template: templates/build.yml
        