# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pr:
  branches:
    include:
    - main
    exclude:
    - release/*

stages:
- stage: build
  displayName: build
  pool:
    name: On-Premise # Runs on OnPrem Windows (for now)
    demands:
    - Agent.Name -equals $(buildAgentName)
    # vmImage: 'ubuntu-latest' # Runs on Hosted Ubuntu VM
  jobs:
  - job: Build
    workspace:
      clean: all
    steps:
    - template: templates/build.yml
  
- stage: deploy
  dependsOn: build
  displayName: Deploy to IIS
  condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/main'),eq(variables['Build.SourceBranch'], 'refs/heads/release'),eq(variables['Build.SourceBranch'], 'refs/heads/ChinaBuild')))
  jobs:
  - deployment: DeploytoIIS
    environment:
      name: Staging
      resourceType: VirtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
          - template: templates/deploy.yml

- stage: test
  dependsOn: deploy
  displayName: Tests - CodeAuditor
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['CHINA_BUILD'], 'FALSE'))
  pool:
    name: On-Premise # Runs on OnPrem Windows (for now)
    demands:
    - Agent.Name -equals $(buildAgentName)
    # vmImage: 'ubuntu-latest' # Runs on Hosted Ubuntu VM
  jobs:
  - job: Test
    steps:
    - template: templates/test.yml
