name: Scheduled CodeAuditor Scan

# Schedule Scan for SSW People at 1pm every Wednesday
on: 
  schedule:
  - cron: "0 13 * * 3"

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions: 
      issues: write
    steps:
      - uses: actions/checkout@v3
      - name: CodeAuditor Workflow
        uses: SSWConsulting/codeauditor-scan-site@1.0.0
        with:
          # Your CodeAuditor token
          token: ${{ secrets.CODEAUDITOR_TOKEN }}
          # Your Scan URL
          url: https://www.ssw.com.au/people/
          # Your GitHub Token
          GitHub_Token: ${{ github.token }}
